### ISSUE TITLE
Vise antall konsulenter i gitt søk

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#109]
Design tilgjengelig i figma. 

Skal bare vise tallet av antall konsulenter i et gitt søk

**Comment by carinamnk** [comment]
Et tall som viser antall konsulenter i lista (før og etter filtrering/søk)

![Image](https://github.com/varianter/vibes/assets/110613510/f7abe11c-015e-41c6-8197-a0680ab09bc3)

**Comment by carinamnk** [comment]
https://www.figma.com/file/yH4nVt7HNzUUNTcrKAFys7/Bemanning-3.0?type=design&node-id=904%3A2430&mode=design&t=jOdxFLXg7RaawO5p-1
