### ISSUE TITLE
Sentrer navn og RÅ-år vertikalt (CSS)

### ISSUE THREAD

**Issue by yelodevopsi** [varianter/vibes#184]

**Comment by sigtheidiot** [comment]
Hva er issuet her? Klarer ikke å skjønne fra figma skissene at det er noen forskjell fra hvordan det er i dev og tegningene? 😅

**Comment by yelodevopsi** [comment]
Det ble nevnt på on-the-fly i møtet igår 🙃 Så vet ikke helt om den er relevant lenger? tror det var @mathildehaugum som så det

**Comment by yelodevopsi** [comment]
Closing since its not relevant any longe
