### ISSUE TITLE
Fix filter-text 

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#213]
Filter-text should be `"Jonas", Bergen, Oslo, 0-2, 3-4, 5-7` etc

**Comment by yelodevopsi** [comment]
Confirming that this is fixed:

Closing task

<img width="764" alt="image" src="https://github.com/varianter/vibes/assets/11426361/c20aeb57-3676-41b7-8ecd-0a6c52881960">

**Comment by yelodevopsi** [comment]
Solved in #215
