### ISSUE TITLE
Fjerne "Rå"-greier, endre til erfaring

### ISSUE THREAD

**Issue by sigtheidiot** [varianter/vibes#231]
- [ ] Endre "Rå-grupper" til "Erfaring" 
- [ ] Endre "RÅ år" til "års erfaring"
- [ ] Fjerne "DU ER RÅ" fra trekkspill

**Comment by yelodevopsi** [comment]
![Image](https://github.com/varianter/vibes/assets/11426361/a76d648e-dbf5-40d3-8d55-740e37221b23)

**Comment by sigtheidiot** [comment]
Closed with #240
