### ISSUE TITLE
Tilgjengeliggjøre data for bemanning i API

### ISSUE THREAD

**Issue by sigtheidiot** [varianter/vibes#233]
Lag API-endepunkt for bemanning

- [ ] Ledig tid
- [ ] Tenativ ledig tid
- [ ] Typer allokert tid per prosjekt/status
- [ ] Per kunde (AKVA, SVV,...)
- [ ] Permisjon uten lønn,

**Comment by yelodevopsi** [comment]
URL til API /staffing ?
