### ISSUE TITLE
Oppdater "Åpne filter"-knapp

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#291]
Endre fra knappen som sitter fast på venstre side av skjermen til en knapp som ligger på linje med "Aktive filter"-stringen. Legg også til en snarvei, der trykking på "-" åpner sidemenyen med filter

![Image](https://github.com/varianter/vibes/assets/69193134/695b629b-eb5a-4a99-aa58-cc3d1c204922)

**Comment by yelodevopsi** [comment]
Closing since this is "done" jonas 👏
