### ISSUE TITLE
Configure Azure hosting (docker/app service etc)

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#5]
- [x] Configure Dev environment and test deploy
- [ ] Config Prod environemnt and test deploy

- [x] - [x] Decide on solution (functions, app service, docker, osv)

**Comment by yelodevopsi** [comment]
Refine workflow with
**https://github.com/gregrickaby/nextjs-github-pages/blob/main/.github/workflows/deploy.yml**

**Comment by yelodevopsi** [comment]
Moving production task to later (copy of dev-environment Web App setup?)
* Will Focus on PR generated builds + development first.
