### ISSUE TITLE
Fjern "Organization"-entiteten fra databasen

### ISSUE THREAD

**Issue by jonasbjoralt** [varianter/vibes#95]
Det er nå én app pr organisasjon, så alle entiteter har samme org implisitt.

**Comment by yelodevopsi** [comment]
Ser et par hikkups her:
* pga at jeg må nå dependency-injecte AppSettings, så bør vi gå over på et Repository-pattern. DomainModels nå gir ikke helt mening, da det strengt tatt er Entities mot databasen, men har også noe GetHours* logikk her som egentlig hører utenom.

**Comment by yelodevopsi** [comment]
Har fått løst dette på en grei måte etter diskusjon med @jonasbjoralt
